spring.application.name=demo-cookies
spring.application.name=demo-cookies

spring.datasource.url=jdbc:postgresql://localhost:5432/demo_cookies_db
spring.datasource.username=postgres
spring.datasource.password=1076904350
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=3b6f2a8c9d1e4f7a0b5c8d2e6f9a3b7c1d4e8f2a5b9c3d7e1f4a8b2c6d0e5f9a
jwt.expiration=86400000